
import Head from 'next/head'
import { Inter } from '@next/font/google'
import { BrandHeader } from './components/brandHeader'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Nike store</title>
        <meta name="description" content="Generated by atef chelaghma" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BrandHeader />
      <header>
      
      </header>
      <main>
       
      </main>
    </>
  )
}
